source {C:/Xilinx/data/projnav/scripts/VsimStopServer.tcl}
-- Auto Generated by Project Navigator to simulate
-- HDL Bencher Annotated Test Bench
--
vlib work
onbreak {resume}
onerror {quit -code 99 -force}
onElabError {resume}
vcom -explicit  -93 "ALU.vhd"
vcom -explicit  -93 "ALU_TBW.ant"
vsim -t 1ps   -lib work ALU_TBW
run -all
quit -force
